language: node_js
node_js:
  - '4'

env:
  global:
    - CXX=g++-4.8
    - ENCRYPTION_LABEL: "02f48b5e2393"
    - COMMIT_AUTHOR_EMAIL: "patternfly-build@redhat.com"
    - TRIGGER_REPO_SLUG: "patternfly/patternfly-atomic"
    - TRIGGER_REPO_BRANCH: "master"


addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

cache:
  directories:
    - node_modules

before_install:
  - 'git checkout -B $TRAVIS_BRANCH' # Reconcile detached HEAD

script:
  - npm run gulp patternlab:build

after_success:
  - npm run publish-travis
